swagger: "2.0"
info:
  description: "This is a service that will facilitate the invite token generation and validationfor the Catalyst Experience App. An invite token is a 6 to 12 digit alphanumeric string that app admin can share with potential customers."
  version: "1.0.0"
  title: "App Invite Service"
  contact:
    email: "thanachot.coon@gmail.com"
host: "app-invite-service.herokuapp.com"
basePath: "/"
tags:
- name: "admin"
  description: "endpoint for admin"
- name: "public"
  description: "endpoint for public user"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
schemes:
- "https"
paths:
  /token_list:
    post:
      tags:
      - "admin"
      summary: "get an overview of active/inactive token"
      description: ""
      operationId: "TokenListEndpoint"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "header"
        type: "string"
        name: "Authorization"
        description: "use basic authen (fix value)"
        required: true
        default: "Basic a2mJIp6IOyZihYvw60WSwzprkB8AHGyOxtvmh0k1U4Lr0upv1LVpi4y"
      - in: "header"
        type: "string"
        name: "Content-Type"
        description: "use application/json (fix value)"
        required: true
        default: "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/TokenListResponse"
        "401":
          description: "Unauthorized"
        "500":
          description: "System Error"

  /token_disable:
    post:
      tags:
      - "admin"
      summary: "set token to inactive"
      description: ""
      operationId: "TokenDisableEndpoint"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "header"
        type: "string"
        name: "Authorization"
        description: "use basic authen (fix value)"
        required: true
        default: "Basic a2mJIp6IOyZihYvw60WSwzprkB8AHGyOxtvmh0k1U4Lr0upv1LVpi4y"
      - in: "header"
        type: "string"
        name: "Content-Type"
        description: "use application/json (fix value)"
        required: true
        default: "application/json"
      - in: "body"
        name: "body"
        description: "Token for disable"
        required: true
        schema:
            $ref: "#/definitions/Token"
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "500":
          description: "System Error"
          
  /token_generate:
    post:
      tags:
      - "admin"
      summary: "create new token"
      description: ""
      operationId: "TokenGenerateEndpoint"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "header"
        type: "string"
        name: "Authorization"
        description: "use basic authen (fix value)"
        required: true
        default: "Basic a2mJIp6IOyZihYvw60WSwzprkB8AHGyOxtvmh0k1U4Lr0upv1LVpi4y"
      - in: "header"
        type: "string"
        name: "Content-Type"
        description: "use application/json (fix value)"
        required: true
        default: "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Token"
        "401":
          description: "Unauthorized"
        "500":
          description: "System Error"
          
  /token_detail:
    post:
      tags:
      - "public"
      summary: "create new token"
      description: ""
      operationId: "TokenDetailEndpoint"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "header"
        type: "string"
        name: "Content-Type"
        description: "use application/json (fix value)"
        required: true
        default: "application/json"
      - in: "body"
        name: "body"
        description: "Get Token Detail"
        required: true
        schema:
            $ref: "#/definitions/Token"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Status"
        "401":
          description: "Unauthorized"
        "500":
          description: "System Error"

definitions:

  TokenListResponse:
    type: "object"
    properties:
      token_list:
        type: array
        items:
          $ref: '#/definitions/TokenList'
          
  TokenList:
    type: "object"
    properties:
      token:
        type: string
        minLength: 6
        maxLength: 12
        default: "aq21V2das"
      status:
        type: string
        enum:
          - "active"
          - "inactive"
      created_at:
        type: string
        format: "date-time"
      expired_at:
        type: string
        format: "date-time"
        
  Token:
    type: "object"
    properties:
      token:
        type: string
        minLength: 6
        maxLength: 12
        default: "aq21V2das"
        
  Status:
    type: "object"
    properties:
      status:
        type: string
        enum:
          - "active"
          - "inactive"
 